### PR TITLE
support for auto-recompiling (-w|--watch option)

### PR DESCRIPTION
**Pull request by FND**
as proposed/discussed in #19 

please note the commit message in 4a65984da9d4693d71a5d10a1eb014366ddb0926

I'll add some documentation to the README if this seems acceptable - but I'm not sure how to write sensible tests for this

sample project: https://gist.github.com/FND/8334c63229867e33feae - to test it with this branch:

```
$ git clone https://github.com/FND/postcss-cli.git
$ cd postcss-cli
$ git checkout watch
$ git clone https://gist.github.com/8334c63229867e33feae.git sample
$ cd sample
$ ../bin/postcss -c postcss.config.js -w
```

### CODE REVIEW

**Comment by pirxpilot** [comment]
Thanks. Not sure about the tests either. I'll try to review and merge this weekend.

**Comment by FND** [comment]
I've made an attempt to write tests on a separate branch: https://github.com/FND/postcss-cli/commit/2e33cb4bb810773cf5fc1bf8f7a75a1aaec9f885

Note the commit message; I'm not sure it's a good idea to merge that.

**Comment by pirxpilot** [comment]
Added my comment [to the issue](https://github.com/code42day/postcss-cli/issues/19#issuecomment-122673039) instead of here. Sorry.

**Comment by FND** [comment]
I've added some documentation (feel free to improve; I struggled a bit with the phrasing) and pulled in the tests as suggested.

> `--watch|-w` option only seems to work when `postcss-import` is used - otherwise `postcss-cli` compiles files once and exits.

Good catch! That was a stupid error, fixed in b60f7e5a6bacdf5b9be77439e4d48b08e0f98d81.

**Pull request merged**
