### PR TITLE
try use local package first, global package second

### PR DESCRIPTION
**Pull request by rnons**
This pull request attempts to fix issues like #16, so that we don't need to install postcss plugins to global.

It adds a new dependency `resolve`, which is used in `browserify`

### CODE REVIEW

**Comment by pirxpilot** [comment]
Looks promising. Any chance you could write a simple test to make sure we don't break it in future?

**Comment by pirxpilot** [comment]
Also I don't think we should use that by default. Changing the way `postcss-cli` looks up plugins might break or change existing builds. I am OK with adding `--plugin-dir` option (_better names welcomed_) that would  trigger using `resolve` instead of standard `require`. And `--plugin-dir` without a value could default to `process.cwd()`.
Thoughts?

**Comment by rnons** [comment]
Sorry, I don't see how this can break existing builds, could you please give me some hint?

Would user actually pass value to `--plugin-dir`? I think it's a binary case, either lookup in local or global. So if we choose the adding option approach, how about adding a binary flag called `--resolve-local` or `--local-plugins`?

**Comment by pirxpilot** [comment]
> Sorry, I don't see how this can break existing builds, could you please give me some hint?

Let's say you were using globally installed postcss but you also had some plugins (maybe different version) installed in local `node_modules` - this change would silently cause a different set of plugins to be loaded. That's against [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) ;-) 

BTW: I do think everyone who cares about reproducible build results already have all the tools and plugins installed locally and locked in `npm_shrinkwrap`, but still...

> Would user actually pass value to --plugin-dir? I think it's a binary case, either lookup in local or global. So if we choose the adding option approach, how about adding a binary flag called --resolve-local or --local-plugins?

Well, if you happen to have Makefile located in a directory different than `node_modules` location, you'd want to pass an argument to this option. `pwd` might be a reasonable default.
That said - I am totally OK if you leave it to implement to someone who actually needs it. And `--local-plugins` as an option name seems OK to me. Even it it were to take an argument in future.

**Comment by rnons** [comment]
I just added a `--local-plugins` option, but I don't how to write a test for it. Should I add a `fake_pkg` to `node_modules` then test with and without `--local-plugins` option?

**Comment by pirxpilot** [comment]
You'll need to create a small subtree in the test directory with at least one dummy package (no need to publish anything to npm) and test it by running postcss from that directory. I can help with Makefile once you get started. You can check out 36d5ad2bd6 to see how you can change directory in the Makefile test.
I'll help if you get stuck.

Also please describe a new option in Readme.

**Comment by rnons** [comment]
I have just added a test, please review

**Comment by pirxpilot** [comment]
Thank you! Released as 2.3.0

**Pull request merged**
