### PR TITLE
add option to mirror input directory structure in the output folder

### PR DESCRIPTION
**Pull request by nostalgicdodo**
implemented https://github.com/code42day/postcss-cli/issues/36

### CODE REVIEW

**Comment by pirxpilot** [comment]
Nice. Thanks. Couple of suggestions:
- fix the lint issues - missing semicolon is why the build is failing ATM
- let's use sync versions of `mkdirp` - we use sync versions of all other `fs` functions 
- try to write a test for it - ample examples in the Makefile - I'll help if you get stuck
- as you implemented it `hierarchy` changes the meaning of the `dir` option - it might be simpler if we let user specify an argument for `hierarchy` making it similarly to `output` and `dir` (and mutually exclusive with the two) - to tell the truth I would probably pick a different names for those but it might be too late for that...

Other - less important:
- there is no reason to allow src as directory for this option only - it would be less surprising for a user if we checked if `input` is a directory and apply `*_/_.css' filter to it regardless of the other options. To keep things simple we can only deploy this trick if we are dealing with a single entry in inputs array.

**Comment by pirxpilot** [comment]
postcss-cli is now maintanained in [postcss/postcss-cli](https://github.com/postcss/postcss-cli)

**Comment by dotnetCarpenter** [comment]
Is this feature in postcss-cli@2.5.1? I can't find it or a work-around to do this.

**Comment by Hirse** [comment]
There seems to be an open PR:
https://github.com/postcss/postcss-cli/pull/31

**Pull request closed without merging**
