### PR TITLE
Default file name for configuration options

### PR DESCRIPTION
**Pull request by sebdeckers**
Command line arguments override the defaults. The configuration file is
optional (no pun intended).

### CODE REVIEW

**Comment by pirxpilot** [comment]
Question: will it have the effect of parsing `postcss.json` _only_ if -c|--config is specified? Or will it magically parse it whenever such file is present in `pwd`?

**Comment by sebdeckers** [comment]
1. `yargs@3.15.0` fixes warnings with missing config files when a default filename is set. Reference: https://github.com/bcoe/yargs/issues/184#issuecomment-118735973
2. If the config file is present, it will be loaded. This is similar to tools like Mocha or Babel. Keeps commands shorter which is great for `package.json` scripts. Would you prefer a different default config file name?

**Comment by pirxpilot** [comment]
> If the config file is present, it will be loaded. This is similar to tools like Mocha or Babel. Keeps commands shorter which is great for package.json scripts. Would you prefer a different default config file name?

The name if fine. I was a bit worried that we will pick up the config file event if `--config` option is not used, which would be a bit too much magic for my taste.

That said - I am probably doing something wrong but I am yet to successfully use this.

When I specify the name of config file like that:

```
../bin/postcss -u postcss-url -c postcss.json -o build/default-config.css in.css
```

Everything seem to be OK.
Howewer this:

```
../bin/postcss -u postcss-url -c -o build/default-config.css in.css
```

Produces:

```
Invalid JSON config file: true
```

Any insights? Feel free to fix the test if I am doing something wrong. It's in [pr/31](https://github.com/code42day/postcss-cli/tree/pr/31) branch.
Failing Travis build is [here](https://travis-ci.org/code42day/postcss-cli/builds/85540548)

**Comment by pirxpilot** [comment]
I don't think `postcss-cli` should be grabbing config options from the file in the current directory without making it explicit in the command line. If we want to use a default config file, its location should be relative to the CSS sources, and not to the working directory. I was under impression this PR required passing empty `--config` option to trigger that behavior, but I was wrong about it.

Just to be clear: I am OK with implementing something that would look for `postcss` options in the way that `jshint` or `mocha` are looking for `.jshintrc` and `mocha.opts` respectively. That ensures the result of running the tools does not depend on the directory from which the tool is run.

**Comment by sebdeckers** [comment]
Do you mean it should travel up the directory tree until a configuration file is found? I don't think `yargs` currently supports that but it could be a useful feature to propose. Let me know and I will look into it.

I also did some checking how other tools do this:

#### npm

Travels up the directory tree until it finds a `package.json`. The file name is fixed.

#### babel

Looks for `.babelrc` and travels up the parent directory until one is found. Has an option to set the config file path.

#### mocha

Looks for `./test/mocha` from cwd. The file path is configurable. Does not travel up parent directories.

Interestingly:
https://github.com/mochajs/mocha/issues/1721#issuecomment-110917070

> I think [the current implementation of mocha.opts] should be completely removed and replaced with an "rc" file, which would be either .ini, .json or .yaml.
> –boneskull (contributor to mocha)

#### jscs

http://jscs.info/overview#-config-c

> If there is no --config option specified, jscs it will consequentially search for jscsConfig option in package.json file then for .jscsrc (which is a just JSON with comments) and .jscs.json files in the current working directory then in nearest ancestor until it hits the system root.

#### jshint

http://jshint.com/docs/cli/

> jshint will look for this configuration in a number of locations, stopping at the first positive match:
> - The location specified with the --config flag
> - A file named package.json located in the current directory or any parent of the current directory (the configuration should be declared as the jshintConfig attribute of that file's JSON value)
> - A file named .jshintrc located in the current directory or any parent of the current directory
> - A file named .jshintrc located in the current user's "home" directory (where defined)

**Comment by pirxpilot** [comment]
> Do you mean it should travel up the directory tree until a configuration file is found? I don't think yargs currently supports that but it could be a useful feature to propose. Let me know and I will look into it.

Yup - `yargs` does not support it. And I am not sure, if it even should. But we may be able to put something together using [commondir](https://www.npmjs.com/package/commondir) and [nearest-file](https://www.npmjs.com/package/nearest-file).

**Comment by sebdeckers** [comment]
Update: I've created a package called [nearest-file-path](https://www.npmjs.com/package/nearest-file-path). It is inspired by `nearest-file` -- thanks for the suggestion! It returns the path instead of the file contents.

Then created a PR on yargs to discuss the directory tree traversal feature. See: https://github.com/bcoe/yargs/pull/280

**Comment by pirxpilot** [comment]
I am confused: it looks to me like you want `yargs` to look for configuration file in the parent directory of `cwd`, right? But that's not what would be needed for `postcss`. To be clear: I am OK with `postcss` looking for config in path relative to the files it is parsing, not relative to the directory in which it happens to be executed.

**Comment by sebdeckers** [comment]
I think yargs allows passing any path as the `cwd`. It merely defaults to `process.cwd()`.

What is the path of the files `postcss` is parsing? Example would help me understand and allow me to modify this PR accordingly.

**Comment by pirxpilot** [comment]
> I think yargs allows passing any path as the cwd. It merely defaults to process.cwd().

You can pass path to `yargs` but that's now used to rebase the name of the executable. Things we'll start to look strange if you pass the name of the directory in which you want `yargs` look for config file there. Also there is a chicken and egg problem in this approach: we'll only know which directory to use if we first use `yargs` to give us the name of the files we should parse.

> What is the path of the files postcss is parsing? Example would help me understand and allow me to modify this PR accordingly.

Example:

```
home
  project
    css
       -postcss.json
       subdir
         -page1.css
    build
```

If one runs:

```
> cd project
> postcss -d build css/subdir/page1.css  
```

I think postcss in that case should pickup config `home/project/css/postcss.json`
In more general case I think that if postcss has to have some kind of automatic config lookup, it should start looking for config in the directory that is a common parent of all the CSS files it works on.

**Comment by sebdeckers** [comment]
Any examples of tools which have solved this chicken and egg problem?

In the given example of a known sub-directory, the solution is `postcss
--config css/postcss.json`. Where the config file contains `{ "d": "build",
"i": "css/subdir/page1.css" }`. Should work in any sub-directory of the
project.

Common parent of all CSS files feels arbitrary and unconventional. Why not
CWD or root of `package.json` for example?

On Sun, Oct 18, 2015 at 8:46 PM, Damian Krzeminski <notifications@github.com

**Comment by pirxpilot** [comment]
I think that using `cwd` for config is arbitrary and even dangerous. What I am hearing is that you think using source location for config is arbitrary and unconventional. It does not look like we can square it :-)

**Comment by sebdeckers** [comment]
@pirxpilot Fair enough. :+1: Btw how do you feel about [rc](https://www.npmjs.com/package/rc)?

**Pull request closed without merging**
