### PR TITLE
tweaked watch-related internals

### PR DESCRIPTION
**Pull request by FND**
just a few minor tweaks; see commit messages for details

### CODE REVIEW

**Comment by FND** [comment]
By the way, @pirxpilot: What's your stance on using ES6 syntax, particularly arrow functions? Presumably a modern version of Node can be expected these days?

**Comment by pirxpilot** [comment]
I think `postcss-cli` should support the same versions of node that `postcss` supports. I just updated .travis.yml to include '0.12' and 'stable' (because that's what postcss had). I am not 100% sure, but I think that fat arrow functions were either not supported or required some special parameter on 0.12 - and I'd rather not make live more difficult for people who still have to use that.
That said if there is a way of enabling it transparently those stuck with 0.12 or if postcss drops 0.12 compatibility I am all for it.

**Comment by FND** [comment]
You're right, arrow functions still require the `--harmony` flag in 0.12. I don't think we can control such features, i.e. it would be up to the user to provide the aforementioned flag - and we have no way of informing them at runtime. So it's probably not worth the trouble at this point, let's revisit in a few months.

**Comment by pirxpilot** [comment]
Thank you!
Released as 2.3.1

**Pull request merged**
